---

- name: install Percona repo
  yum: name={{ repo["url_percona"] }} state=present

- name: install mysql
  yum: name=Percona-Server-server-56.x86_64 state=latest

- name: start mysql
  service: name=mysql state=started enabled=yes

- name: install python MySQL module
  yum: name=MySQL-python state=latest

- name: create database for wordpress
  mysql_db: name={{ wordpress["db_name"] }} state=present

- name: create user for wordpress databases
  mysql_user:
    name={{ wordpress["db_user"] }}
    password={{ wordpress["db_pass"] }}
    priv={{ wordpress["db_name"] }}.*:ALL
    host="%"
    state=present
