---

- name: install repo Webtatic (for PHP5.6)
  yum: name={{ repo["url_webtatic"] }} state=present

- name: install nginx
  yum: name=nginx state=latest

- name: configure nginx (main config)
  template:
    src=nginx/nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: mkdir for root www
  file: path=/var/www/ state=directory

- name: download wordress
  get_url: url=https://wordpress.org/wordpress-{{ wordpress["version"] }}.tar.gz dest=/tmp/wordpress.tar.gz

- stat: path=/tmp/wordpress.tar.gz
  register: wp_src

- name: unpack wordpress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www copy=no
  when: wp_src.stat.exists == True

- name: configure wordpress
  template:
    src=wordpress/wp-config.php.j2
    dest=/var/www/wordpress/wp-config.php

- name: restore permissions
  file:
    path=/var/www/wordpress
    state=directory
    mode=755 owner=nginx group=nginx
    recurse=yes

- name: install php-fpm
  yum: name=php70w-fpm state=latest

- name: configure php-fpm (disable old pools)
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.conf.original creates=/etc/php-fpm.d/www.conf.original

- name: configure php-fpm
  template: src=php-fpm/wp.conf.j2 dest=/etc/php-fpm.d/wp.conf
  notify: restart php-fpm

- name: start php-fpm
  service: name=php-fpm state=started enabled=yes

- name: install PHP
  yum: name={{ item }} state=latest
  with_items:
    - php70w
    - php70w-mysqlnd